# Generated by Django 2.2.3 on 2019-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_backup', '0007_remove_backupsettings_compress'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Client Secret')),
                ('authorization_url', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Authorization URL')),
                ('user_code', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='User Code')),
                ('latest_sync', models.DateTimeField(blank=True, default=None, help_text='Timestamp of latest sync with Google Drive. Automatically updated by application.', null=True, verbose_name='Latest sync')),
                ('next_sync', models.DateTimeField(blank=True, default=None, help_text='Timestamp of next sync with Google Drive. Automatically updated by application.', null=True, verbose_name='Next sync')),
                ('folder_name', models.CharField(blank=True, default='dsmr-backup', max_length=24, null=True, verbose_name='Google Drive Folder Name')),
                ('folder_id', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('interval', models.IntegerField(default=5)),
                ('access_token', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('refresh_token', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('device_code', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('token_expiry', models.DateTimeField(default=None, null=True, blank=True)),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Google Drive configuration',
                'default_permissions': (),
            },
        ),
    ]
